# Generated by Django 4.2.1 on 2023-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_post.png', upload_to='post/'),
        ),
    ]
