# Generated by Django 4.2.1 on 2023-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='post_thumbnails/default_post.png', upload_to='post_thumbnails/'),
        ),
    ]
