# Generated by Django 4.2.1 on 2023-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='dog_pictures')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
